# ReadTheDocs configuration file for ProteusJS
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, set of tools, and environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - requirements: docs/requirements.txt

# Additional configuration
search:
  ranking:
    api/core-api.rst: 2
    getting-started/quick-start.rst: 3
    features/container-queries.rst: 2
    features/accessibility.rst: 2

# Submodules configuration (if needed)
submodules:
  include: []
  exclude: all
  recursive: false
