# Configuration file for the Sphinx documentation builder.
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'ProteusJS'
copyright = '2025, sc4rfurry'
author = 'sc4rfurry'

# The full version, including alpha/beta/rc tags
release = '2.0.0'
version = '2.0.0'

# Enhanced project title with branding
html_title = f'{project} v{version} Documentation'
html_short_title = 'ProteusJS'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',  # Put MyST parser first for proper registration
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',
    'sphinx_tabs.tabs',
    'sphinx_design',
    'sphinx_rtd_theme',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '__pycache__',
    '*.pyc'
]

# The suffix(es) of source filenames.
# Simple format for maximum compatibility
source_suffix = ['.rst', '.md']

# MyST parser configuration - enhanced for Phase 2
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

# MyST parser options for enhanced functionality
myst_heading_anchors = 3
myst_footnote_transition = True

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Enhanced theme options for ProteusJS v2.0.0 branding
html_theme_options = {
    'analytics_id': '',  # Add Google Analytics ID if needed
    'logo_only': True,  # Show only logo, not project name
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#667eea',
    # Enhanced navigation options
    'collapse_navigation': False,  # Keep navigation expanded for better UX
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
    # ProteusJS branding
    'github_url': 'https://github.com/sc4rfurry/ProteusJS',
    'twitter_url': 'https://twitter.com/proteusjs',
}

# Use html_baseurl instead of deprecated canonical_url
html_baseurl = 'https://proteusjs.readthedocs.io/'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom CSS and JS files - re-enabled for visual enhancement
html_css_files = ['css/custom.css']
html_js_files = ['js/custom.js']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ProteusJSdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    'preamble': '',

    # Latex figure (float) alignment
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ProteusJS.tex', 'ProteusJS Documentation',
     'ProteusJS Team', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'proteusjs', 'ProteusJS Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ProteusJS', 'ProteusJS Documentation',
     author, 'ProteusJS', 'Shape-shifting responsive design library.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
epub_identifier = 'https://github.com/sc4rfurry/ProteusJS'

# A unique identification for the text.
epub_uid = 'ProteusJS'

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for copybutton extension ----------------------------------------

copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# MyST parser extensions already configured above

# -- Custom configuration ----------------------------------------------------

# HTML context for template variables
html_context = {
    'display_github': True,
    'github_user': 'sc4rfurry',
    'github_repo': 'ProteusJS',
    'github_version': 'main',
    'conf_py_path': '/docs/',
    'source_suffix': source_suffix,
}

# Logo configuration - Professional SVG logo system
html_logo = '_static/images/logo.svg'
html_favicon = '_static/images/favicon.svg'

# Note: logo_only already set in html_theme_options above

# Ensure logo displays properly
html_static_path = ['_static']
html_css_files = [
    'css/custom.css',
]

# Enhanced HTML context for ProteusJS v2.0.0
html_context = {
    'display_github': True,
    'github_user': 'sc4rfurry',
    'github_repo': 'ProteusJS',
    'github_version': 'main',
    'conf_py_path': '/docs/',
    'source_suffix': source_suffix,
    'current_version': '2.0.0',
    'version_slug': 'v2.0.0',
    'downloads': [
        ('PDF', 'https://proteusjs.readthedocs.io/_/downloads/en/latest/pdf/'),
        ('HTML', 'https://proteusjs.readthedocs.io/_/downloads/en/latest/htmlzip/'),
        ('Epub', 'https://proteusjs.readthedocs.io/_/downloads/en/latest/epub/'),
    ],
}

# Enhanced sidebar configuration
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# Search configuration
html_search_language = 'en'

# Version warning
html_show_sourcelink = True
html_show_sphinx = True

# Custom sidebar
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# -- Custom functions --------------------------------------------------------

def setup(app):
    """Enhanced setup function for ProteusJS v2.0.0 visual branding."""
    import os

    # Add custom CSS and JS files for visual enhancement
    static_dir = os.path.join(os.path.dirname(__file__), '_static')

    # Enhanced CSS for professional styling
    css_file = os.path.join(static_dir, 'css', 'custom.css')
    if os.path.exists(css_file):
        app.add_css_file('css/custom.css')
        print("✅ ProteusJS custom CSS loaded")

    # Enhanced JavaScript for interactive features
    js_file = os.path.join(static_dir, 'js', 'custom.js')
    if os.path.exists(js_file):
        app.add_js_file('js/custom.js')
        print("✅ ProteusJS custom JavaScript loaded")

    # Add custom HTML context for branding
    app.add_html_theme_path = []

    return {
        'version': '2.0.0',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }

# -- Enhanced SEO and metadata for ProteusJS v2.0.0 -------------------------

html_meta = {
    'description': 'ProteusJS v2.0.0 - Native-first web development primitives with modern platform APIs, accessibility, and performance optimization.',
    'keywords': 'web platform apis, navigation api, view transitions, popover api, scheduler api, pwa, accessibility, performance, typescript, javascript',
    'author': 'sc4rfurry and ProteusJS Team',
    'viewport': 'width=device-width, initial-scale=1.0',
    'robots': 'index, follow',
    'theme-color': '#667eea',
    'msapplication-TileColor': '#667eea',
    # Open Graph meta tags
    'og:title': 'ProteusJS v2.0.0 Documentation',
    'og:description': 'Native-first web development primitives for modern applications with comprehensive API documentation.',
    'og:type': 'website',
    'og:url': 'https://proteusjs.readthedocs.io/',
    'og:image': 'https://proteusjs.readthedocs.io/_static/images/og-image.svg',
    'og:image:width': '1200',
    'og:image:height': '630',
    'og:site_name': 'ProteusJS Documentation',
    # Twitter Card meta tags
    'twitter:card': 'summary_large_image',
    'twitter:site': '@ProteusJS',
    'twitter:creator': '@sc4rfurry',
    'twitter:title': 'ProteusJS v2.0.0 Documentation',
    'twitter:description': 'Native-first web development primitives for modern applications.',
    'twitter:image': 'https://proteusjs.readthedocs.io/_static/images/og-image.svg',
    # Additional meta tags
    'application-name': 'ProteusJS Documentation',
    'apple-mobile-web-app-title': 'ProteusJS Docs',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
}

# -- Build configuration -----------------------------------------------------

# Suppress warnings
suppress_warnings = [
    'image.nonlocal_uri',
    'config.cache',
    'toc.excluded',
    'misc.highlighting_failure'
]

# Nitpicky mode
nitpicky = False

# Keep going on errors
keep_going = True
