# Configuration file for the Sphinx documentation builder.
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'ProteusJS'
copyright = '2024, ProteusJS Team'
author = 'ProteusJS Team'

# The full version, including alpha/beta/rc tags
release = '1.0.0'
version = '1.0.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',
    'sphinx_tabs.tabs',
    'myst_parser',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': None,
    '.md': 'myst_parser',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  See the documentation for the theme you are using for more info.
html_theme_options = {
    'canonical_url': 'https://proteusjs.readthedocs.io/',
    'analytics_id': '',  # Add Google Analytics ID if needed
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#667eea',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom CSS files
html_css_files = [
    'css/custom.css',
]

# Custom JavaScript files
html_js_files = [
    'js/custom.js',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ProteusJSdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    'preamble': '',

    # Latex figure (float) alignment
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ProteusJS.tex', 'ProteusJS Documentation',
     'ProteusJS Team', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'proteusjs', 'ProteusJS Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ProteusJS', 'ProteusJS Documentation',
     author, 'ProteusJS', 'Shape-shifting responsive design library.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
epub_identifier = 'https://github.com/sc4rfurry/ProteusJS'

# A unique identification for the text.
epub_uid = 'ProteusJS'

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for copybutton extension ----------------------------------------

copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# -- Options for MyST parser -------------------------------------------------

myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

# -- Custom configuration ----------------------------------------------------

# HTML context for template variables
html_context = {
    'display_github': True,
    'github_user': 'sc4rfurry',
    'github_repo': 'ProteusJS',
    'github_version': 'main',
    'conf_py_path': '/docs/',
    'source_suffix': source_suffix,
}

# Logo configuration
html_logo = '_static/images/logo.png'
html_favicon = '_static/images/favicon.ico'

# Social links
html_theme_options.update({
    'github_url': 'https://github.com/sc4rfurry/ProteusJS',
    'twitter_url': 'https://twitter.com/proteusjs',
})

# Search configuration
html_search_language = 'en'

# Version warning
html_show_sourcelink = True
html_show_sphinx = True

# Custom sidebar
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# -- Custom functions --------------------------------------------------------

def setup(app):
    """Custom setup function for Sphinx."""
    app.add_css_file('css/custom.css')
    app.add_js_file('js/custom.js')
    
    # Add custom directives or roles here if needed
    pass

# -- SEO and metadata --------------------------------------------------------

html_meta = {
    'description': 'ProteusJS - Shape-shifting responsive design library with container queries, fluid typography, and accessibility features.',
    'keywords': 'responsive design, container queries, fluid typography, accessibility, WCAG, CSS, JavaScript, TypeScript',
    'author': 'ProteusJS Team',
    'viewport': 'width=device-width, initial-scale=1.0',
    'robots': 'index, follow',
    'og:title': 'ProteusJS Documentation',
    'og:description': 'Comprehensive documentation for ProteusJS - the modern responsive design library.',
    'og:type': 'website',
    'og:url': 'https://proteusjs.readthedocs.io/',
    'og:image': 'https://proteusjs.readthedocs.io/_static/images/og-image.png',
    'twitter:card': 'summary_large_image',
    'twitter:title': 'ProteusJS Documentation',
    'twitter:description': 'Comprehensive documentation for ProteusJS - the modern responsive design library.',
    'twitter:image': 'https://proteusjs.readthedocs.io/_static/images/twitter-image.png',
}

# -- Build configuration -----------------------------------------------------

# Suppress warnings
suppress_warnings = ['image.nonlocal_uri']

# Nitpicky mode
nitpicky = False

# Keep going on errors
keep_going = True
